2022-01-13 15:33:32,838 [ERROR] [Base.py] [deleteByKey] [line:70] - 根据主键删除数据失败Mongo delete error:127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd5ae3021783ac796b726, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>
2022-01-13 15:33:33,172 [ERROR] [Base.py] [deleteByKey] [line:70] - 根据主键删除数据失败Mongo delete error:127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd5af3a21cfd10ce9c7a7, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>
2022-01-13 15:33:33,239 [ERROR] [Base.py] [deleteByKey] [line:70] - 根据主键删除数据失败Mongo delete error:127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd5afc0182b23725ed9c1, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>
2022-01-13 15:34:02,897 [ERROR] [Base.py] [save] [line:44] - 插入单条数据失败,('Mongo insert_one error:{}', "127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd5ae3021783ac796b726, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>")
2022-01-13 15:34:03,231 [ERROR] [Base.py] [save] [line:44] - 插入单条数据失败,('Mongo insert_one error:{}', "127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd5af3a21cfd10ce9c7a7, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>")
2022-01-13 15:34:03,297 [ERROR] [Base.py] [save] [line:44] - 插入单条数据失败,('Mongo insert_one error:{}', "127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd5afc0182b23725ed9c1, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>")
2022-01-13 15:35:05,607 [ERROR] [Base.py] [deleteByKey] [line:70] - 根据主键删除数据失败Mongo delete error:127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd60b8d25cb5061a7e458, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>
2022-01-13 15:35:05,817 [ERROR] [Base.py] [deleteByKey] [line:70] - 根据主键删除数据失败Mongo delete error:127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd60b3689b342f7ee87dc, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>
2022-01-13 15:35:05,894 [ERROR] [Base.py] [deleteByKey] [line:70] - 根据主键删除数据失败Mongo delete error:127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd60bba753f5e4ebe1c17, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>
2022-01-13 15:35:35,666 [ERROR] [Base.py] [save] [line:44] - 插入单条数据失败,('Mongo insert_one error:{}', "127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd60b8d25cb5061a7e458, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>")
2022-01-13 15:35:35,874 [ERROR] [Base.py] [save] [line:44] - 插入单条数据失败,('Mongo insert_one error:{}', "127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd60b3689b342f7ee87dc, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>")
2022-01-13 15:35:35,953 [ERROR] [Base.py] [save] [line:44] - 插入单条数据失败,('Mongo insert_one error:{}', "127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd60bba753f5e4ebe1c17, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>")
2022-01-13 15:38:01,805 [ERROR] [Base.py] [deleteByKey] [line:70] - 根据主键删除数据失败Mongo delete error:127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd6bb5003eadbc2f06ff6, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>
2022-01-13 15:38:02,140 [ERROR] [Base.py] [deleteByKey] [line:70] - 根据主键删除数据失败Mongo delete error:127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd6bc8ce5a6af5363848d, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>
2022-01-13 15:38:02,199 [ERROR] [Base.py] [deleteByKey] [line:70] - 根据主键删除数据失败Mongo delete error:127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd6bc69ef442296654980, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>
2022-01-13 15:38:31,883 [ERROR] [Base.py] [save] [line:44] - 插入单条数据失败,('Mongo insert_one error:{}', "127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd6bb5003eadbc2f06ff6, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>")
2022-01-13 15:38:32,217 [ERROR] [Base.py] [save] [line:44] - 插入单条数据失败,('Mongo insert_one error:{}', "127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd6bc8ce5a6af5363848d, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>")
2022-01-13 15:38:32,291 [ERROR] [Base.py] [save] [line:44] - 插入单条数据失败,('Mongo insert_one error:{}', "127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd6bc69ef442296654980, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>")
2022-01-13 15:40:35,205 [ERROR] [Base.py] [deleteByKey] [line:70] - 根据主键删除数据失败Mongo delete error:127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd755329d1e0be5521e62, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>
2022-01-13 15:40:35,297 [ERROR] [Base.py] [deleteByKey] [line:70] - 根据主键删除数据失败Mongo delete error:127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd7558f96acd725c8be85, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>
2022-01-13 15:40:35,414 [ERROR] [Base.py] [deleteByKey] [line:70] - 根据主键删除数据失败Mongo delete error:127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd755fb54ff6afe6bdf13, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>
2022-01-13 15:41:05,264 [ERROR] [Base.py] [save] [line:44] - 插入单条数据失败,('Mongo insert_one error:{}', "127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd755329d1e0be5521e62, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>")
2022-01-13 15:41:05,356 [ERROR] [Base.py] [save] [line:44] - 插入单条数据失败,('Mongo insert_one error:{}', "127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd7558f96acd725c8be85, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>")
2022-01-13 15:41:05,476 [ERROR] [Base.py] [save] [line:44] - 插入单条数据失败,('Mongo insert_one error:{}', "127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd755fb54ff6afe6bdf13, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>")
2022-01-13 15:41:37,178 [ERROR] [Base.py] [deleteByKey] [line:70] - 根据主键删除数据失败Mongo delete error:127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd793affca3c2f889a53e, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>
2022-01-13 15:41:37,321 [ERROR] [Base.py] [deleteByKey] [line:70] - 根据主键删除数据失败Mongo delete error:127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd7938d89c6cda6b60d17, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>
2022-01-13 15:41:37,438 [ERROR] [Base.py] [deleteByKey] [line:70] - 根据主键删除数据失败Mongo delete error:127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd79354483aba51b980d0, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>
2022-01-13 15:42:07,235 [ERROR] [Base.py] [save] [line:44] - 插入单条数据失败,('Mongo insert_one error:{}', "127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd793affca3c2f889a53e, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>")
2022-01-13 15:42:07,390 [ERROR] [Base.py] [save] [line:44] - 插入单条数据失败,('Mongo insert_one error:{}', "127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd7938d89c6cda6b60d17, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>")
2022-01-13 15:42:07,495 [ERROR] [Base.py] [save] [line:44] - 插入单条数据失败,('Mongo insert_one error:{}', "127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd79354483aba51b980d0, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>")
2022-01-13 15:43:48,812 [ERROR] [Base.py] [deleteByKey] [line:70] - 根据主键删除数据失败Mongo delete error:127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dfd816657592fd6b0893ef, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused',)>]>
